### ISSUE TITLE
Is there a way to enable Google Analytics or Plausible? Support for SEO?

### ISSUE THREAD

**Issue by aniqatc** [dumptyd/content-theme-blog-minimal#5]
I'm new to static site generators but have been able to edit & deploy Gatsby and Hugo themes with ease. I've also played around with this theme and I really like the simplicity and ease of it. I might consider switching to this, however, SEO and analytics are very important to me - I'd like to know if there's any way to add Google Analytics/Google Tag Manager or Plausible Analytics?  

Additionally, is there any support for SEO and meta data?

**Comment by dumptyd** [comment]
Since you get first-party access to the theme code, you can really add whatever you'd like to it.
So, for adding GA or Plausible analytics (or any other integration that works by adding a code snippet), you can [create an `app.html` file based on these instructions](https://nuxtjs.org/docs/concepts/views/#document-apphtml) and add the respective snippets there.

As for SEO and meta data support, I'd say there's _decent enough_ support for it with post specific meta tags and sitemap generation. Here's the relevant code - https://github.com/dumptyd/content-theme-blog-minimal/blob/f0db72451c7de55844104858c94b40ecbe348130/pages/posts/_slug/index.vue#L75-L89. Other than that, you can also see whatever major search engines have indexed so far from the demo site - [Google](https://www.google.com/search?q=site%3Adumptyd.github.io%2Fcontent-theme-blog-minimal) | [DuckDuckGo](https://duckduckgo.com/?q=site%3Adumptyd.github.io%2Fcontent-theme-blog-minimal).

**Comment by aniqatc** [comment]
Thank you answering my question so thoroughly! I really appreciate it ☺️
